### ISSUE TITLE
关于多卡训练

### ISSUE THREAD

**Issue by YoloEliwa** [zhengli97/PromptKD#11]
请问该repo是否支持多卡训练，作者是否尝试过多卡训练，对性能会不会有影响

**Comment by zhengli97** [comment]
支持的。没有试过多卡，因为我这里一张卡就可以跑起来了。对性能的影响未知。

**Comment by zhengli97** [comment]
目前支持的是nn.DataParallel的，distributed data parallel的情况还不支持

**Comment by zhengli97** [comment]
HiHi 还有什么问题吗 没有问题我就关闭issue了哈 有问题就继续在这个issue下面提 看到了我会回复的
