### ISSUE TITLE
How to calcualte GFlops

### ISSUE THREAD

**Issue by euminds** [zhengli97/PromptKD#13]
![image](https://github.com/zhengli97/PromptKD/assets/46481864/6f6ec3cd-0616-4eb0-bcf1-3d3874a3ba66)
你好，论文里面给出了GFlops，我想问下是怎么测得

**Comment by zhengli97** [comment]
用https://github.com/Lyken17/pytorch-OpCounter 或者 https://github.com/sovrasov/flops-counter.pytorch

**Comment by dana-niu** [comment]
你好  我想问一下 FPS怎么么测的？

**Comment by zhengli97** [comment]
这都是问的什么问题？一个比一个奇怪。fps用显卡测的，不然用什么测？

**Comment by dana-niu** [comment]
好的非常感谢
不是很懂
不好意思

**Comment by zhengli97** [comment]
@euminds 没有问题的话，我就关闭这个issue了哈
