### ISSUE TITLE
        self.VPT_image_trans = Feature_Trans_Module_two_layer(512, 768) 为什么是  512-》768？

### ISSUE THREAD

**Issue by dana-niu** [zhengli97/PromptKD#14]
self.VPT_image_trans = Feature_Trans_Module_two_layer(512, 768)
        image_features = self.VPT_image_trans(image_features)
您好 我想问一下  这个图像特征不是本来就是  768吗
为什么这个会是  512-》768？

**Comment by zhengli97** [comment]
clip vit-b的image feat维度是512

**Comment by dana-niu** [comment]
好的 非常感谢你耐心的回复
