### ISSUE TITLE
直接在PromptSRC的基础上，使用VIT-L/14,不使用知识蒸馏效果怎么样？

### ISSUE THREAD

**Issue by IHikari** [zhengli97/PromptKD#16]
十分感谢！！！

**Comment by zhengli97** [comment]
你的意思是用ViT-L/14 CLIP用PromptSRC训练？这就是teacher的acc

**Comment by IHikari** [comment]
对，作者做了相应实验吗？

**Comment by zhengli97** [comment]
emmm, ViT-L/14 teacher的acc已经在补充材料里面的table 10和table 11里面放了

**Comment by IHikari** [comment]
好的好的，十分抱歉，没看附录。感谢作者的工作
