### ISSUE TITLE
关于训练自己的数据集

### ISSUE THREAD

**Issue by Kirito-Asuna-Yu** [zhengli97/PromptKD#19]
你好，我想问一下，论文里用的数据集都有一个split_zhou_xxx.json文件，是用来划分训练集和测试集的，如果要用自己的数据集，也需要做一个这样的split_xxx.json文件吗

**Comment by zhengli97** [comment]
split.json是对base-to-novel情况下划定类别时候用的，如果是自己的数据直接写一个dataloader和dataset，训练的时候往里面送数据就行，不用管
