### ISSUE TITLE
关于CoOp和PromptKD的GFLOPS和FPS比较

### ISSUE THREAD

**Issue by XpracticeYSKM** [zhengli97/PromptKD#20]
感谢作者的开源，但我对文中效率的比较有点疑问，想请问
1. CoOp在文本分支插入learnable token，在测试前，文本分支可以只进行一次推理，然后复用到所有图像分支。PromptKD在图像分支插入learnable token，对于所有图片都增加了计算时间，还需要经过额外的MLP去进行维度对齐，为什么FPS会更高？
2. 同理1，PromptKD测试时至少FLOPS应该和CoOp一致，为什么会少这么多倍？

或许我有什么细节疏漏，所以导致上述疑惑，希望得到您的解答

**Comment by zhengli97** [comment]
这里考虑的是，对于一个全新的inference场景，coop是包含text encoder进行计算的，promptkd的计算不涉及text encoder，只计算image encoder

**Comment by XpracticeYSKM** [comment]
感谢回复，如何理解一个全新的inference场景呢，指的是一张novel class的类别图片吗，如果是novel class，不是应该也要先计算new  class name的text embedding吗

**Comment by zhengli97** [comment]
这里promptkd的计算部分只考虑student部分的计算，对novel text feature是在第一阶段的训练完成后就有了

**Comment by XpracticeYSKM** [comment]
理解了，感谢作者的耐心解答，我将关闭这个issue。
