### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HXintao** [zhengli97/PromptKD#22]
作者您好，我复现PromptKD的过程中，跑base2new实验，得到的结果与论文中有不小的差距，前三个种子的最高值都达不到论文中的数据，请问会是什么原因呢，一些库的版本不对吗（方便给出一些关键的包的版本吗）？或者是显卡的原因（用的4060ti 16G）？

**Comment by zhengli97** [comment]
Please refer to https://github.com/zhengli97/PromptKD/issues/7

**Comment by HXintao** [comment]
谢谢大佬的回复！刚刚看了一下那个讨论贴，我使用的是您公开的预训练教师模型，不同的数据集也调整了KD_WEIGHT，其余的参数都是下载的时候默认的。有一些数据集不仅是结果与论文差距较大，而且在使用不同的seed时，结果波动较大，Caltech101数据集，KD_WEIGHT:1000.0
Run 1: base:93.7, novel:84.9
Run 2: base: 89.2, novel: 81.3
Run 3: base: 97.6, novel: 93.2
论文中的结果是base:98.91,novel:96.65
观察日志发现，seed1和2的model-best都是在epoch=1的时候得到的，说明在这两个种子中并没有进行有效的训练。

在dtd数据集中就更离谱了，D_WEIGHT:200.0
Run 1: base:58.1, novel:44.9
Run 2: base: 76.6, novel: 62.6
Run 3: base: 52.3, novel: 39.5
论文中的结果是base:85.84,novel:71.37
这个数据集的seed1、2和3的model-best倒是都在训练后期得到的（epoch分别为20、16、19）。

不知道大佬是否遇到过类似的问题，或者能否指出一些我在哪些地方可能出问题了。（感谢！！！）

**Comment by HXintao** [comment]
谢谢大佬的回复！刚刚看了一下那个讨论贴，我使用的是您公开的预训练教师模型，不同的数据集也调整了KD_WEIGHT，其余的参数都是下载的时候默认的。有一些数据集不仅是结果与论文差距较大，而且在使用不同的seed时，结果波动较大，Caltech101数据集，KD_WEIGHT:1000.0
Run 1: base:93.7, novel:84.9
Run 2: base: 89.2, novel: 81.3
Run 3: base: 97.6, novel: 93.2
论文中的结果是base:98.91,novel:96.65
观察日志发现，seed1和2的model-best都是在epoch=1的时候得到的，说明在这两个种子中并没有进行有效的训练。

在dtd数据集中就更离谱了，D_WEIGHT:200.0
Run 1: base:58.1, novel:44.9
Run 2: base: 76.6, novel: 62.6
Run 3: base: 52.3, novel: 39.5
论文中的结果是base:85.84,novel:71.37
这个数据集的seed1、2和3的model-best倒是都在训练后期得到的（epoch分别为20、16、19）。

不知道大佬是否遇到过类似的问题，或者能否指点一下我在哪些地方可能出问题了。（万分感谢！！！）

**Comment by zhengli97** [comment]
caltech的情况没有碰到过，model best一般都是最后几轮的时候训出来的。dtd这个情况我不清楚。
估计是随机采样的时候出的问题，你可以把随机采样的文件删了，然后再去采样试一下。或者多跑一点seed。

**Comment by HXintao** [comment]
多谢大佬的回复，我后面再按照您说的尝试一下。
