### ISSUE TITLE
Request of the Checkpoint File on ImageNet of PromptKD

### ISSUE THREAD

**Issue by QingchenWait** [zhengli97/PromptKD#23]
Thank you for your impressive work!
When reproducing the work, I found that the computational cost of the PromptKD is relatevely high on ImageNet, especially on the cross-dataset tasks.
Could you please share the fine-tuned **.pth file** of **PromptKD** (not the teacher model) on **ImageNet** for cross-dataset task? I would be very grateful if you can!

**Comment by zhengli97** [comment]
I guess I didn't save that model when I changed my internships. Sorry.
