### ISSUE TITLE
$DATA文件夹位置问题

### ISSUE THREAD

**Issue by Wuxiaomann** [zhengli97/PromptKD#25]
请问DATASET.md中提到的$DATA文件夹应该建在哪呢，建好后脚本哪里需要怎么修改呢，初学者不是很懂，感谢解答！
![image](https://github.com/user-attachments/assets/7ad21ab1-7e8a-4b8b-8a46-4c99bd478ce3)

**Comment by zhengli97** [comment]
建议用绝对路径指定到数据集当前目录的上一级目录

**Comment by Wuxiaomann** [comment]
感谢解答，路径问题已解决，请问截图所示报错是数据集文件结构不对导致的吗，我是按照md文档里配置的应该没错呀
![image](https://github.com/user-attachments/assets/3b69b8b9-62fc-42d7-8cc5-fc98b005a16b)

**Comment by Wuxiaomann** [comment]
由于是测试，①我只配置了imagenet文件夹 ②imagenet/images/train文件夹中只放了 120 个类别

**Comment by zhengli97** [comment]
路径不对，没找到数据集，所以data loader为空

**Comment by zhengli97** [comment]
imagenet本身没有release test set用于验证

**Comment by Wuxiaomann** [comment]
感谢回答，已解决
