### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Friendsyou** [zhengli97/PromptKD#26]
使用教师CLIP算text_features时，使用的文本prompt不是预训练好的，而是初始化的a photo of a吗？

**Comment by zhengli97** [comment]
没有太理解你指的是教师clip的训练阶段还是推理阶段？

**Comment by Friendsyou** [comment]
> 没有太理解你指的是教师clip的训练阶段还是推理阶段？

在训练学生clip的时候

**Comment by zhengli97** [comment]
训练学生时的teacher text feature是带有训好的prompt的，不是a photo of a
