### ISSUE TITLE
question in base-to-novel setting

### ISSUE THREAD

**Issue by jihwanp** [zhengli97/PromptKD#27]
Hi i have a question about base-to-novel setting.
When training PromptKD in this setting, do you also use image samples for unseen classes, or do you only use those for the base classes?
It isn’t clear because the paper specifies only cross-dataset as transductive.​
Thanks

**Comment by zhengli97** [comment]
The base-to-novel setting is also transductive ZSL.

**Comment by jihwanp** [comment]
Thanks :)
