### ISSUE TITLE
想问下我的理解正确吗？

### ISSUE THREAD

**Issue by zaiyuzhohg** [zhengli97/PromptKD#30]
在阶段(a) Pre-train a large teacher model，使用的是table 8的Train 数据。
在(b) Student Prompt Distillation阶段，使用的图片是来自table 8的Test Base。
然后（c）Student Inference是在Test Base 和Test Novel上执行。
想问下我的理解正确吗？

**Comment by zhengli97** [comment]
（1）table 8里base class的16 shots有标签数据。（2）无标签的全量数据集（3）是的。
这个问题建议下载一个数据集和代码，你把代码run起来，10分钟不到就能完全知道论文在干什么了。纸上得来终觉浅，得知此事要躬行。

**Comment by zhengli97** [comment]
在知乎上有类似的问题，应该可能是你问的，我都已经回答过了，这个issue我就关闭了哈
