### ISSUE TITLE
How to get the base and novel accuracy and HM?

### ISSUE THREAD

**Issue by Liubinggunzu** [zhengli97/PromptKD#31]
Thanks for the interesting work, I run the base2new_train.sh on caltech101, and I finally get the overall accuracy as follow  
![image](https://github.com/user-attachments/assets/b3483ec4-f46f-4ee2-b943-a700df080737)

So how can I get the  base/novel accuracy and HM as the Table 1 depicted?
Thanks!

**Comment by zhengli97** [comment]
yeah
