### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by LX0930** [zhengli97/PromptKD#34]
请问做Base-to-Novel实验的时候imagenet数据集是不是需要全部下载，100多G有点大，刚开始学不是很懂

**Comment by zhengli97** [comment]
imagenet嫌大可以先拿别的小数据集实验

**Comment by LX0930** [comment]
![image](https://github.com/user-attachments/assets/ed887b03-1edf-4673-99ff-e871db9299d9)
打开stanford_cars链接出现404

**Comment by zhengli97** [comment]
你发这个问题的时候仔细多看看readme，里面的tips都提了

**Comment by LX0930** [comment]
光看running，感谢回答
