### ISSUE TITLE
关于base to novel 数据集设定的问题

### ISSUE THREAD

**Issue by zhangzherui123** [zhengli97/PromptKD#35]
请问下作者，在imagenet下，我理解的base to novel 是只用前500个类别对应的数据集进行蒸馏训练。

但是如下代码的train_x应该是全部类别吧，也就是说训练用到了全部类别数据，然后测试的时候才分了base和novel？

train_x, _ = OxfordPets.subsample_classes(train, test, subsample='all')  

_, base_test = OxfordPets.subsample_classes(train, test, subsample='base')
_, novel_test = OxfordPets.subsample_classes(train, test, subsample='new')

**Comment by zhengli97** [comment]
这个问题我已经回答了很多遍了，知乎的中文解读里，给别人的回复里，建议你多去看看
