### ISSUE TITLE
Excellent work! Where is the code for teacher model training?

### ISSUE THREAD

**Issue by Nevaeh7** [zhengli97/PromptKD#4]

**Comment by zhengli97** [comment]
In our paper, we use PromptSRC to pre-train our ViT-L/14 CLIP teacher model.
In this repo, you can change `PromptKD/scripts/promptsrc/base2new_train.sh line 11 CFG=vit_b16_c2_ep20_batch4_4+4ctx` to `vit_l14_c2_ep20_batch8_4+4ctx`.
Then follow the instructions in `PromptKD/docs/PromptSRC.md` and train your own teacher model.

**Comment by Nevaeh7** [comment]
Thank you for your helpful reply!
