### ISSUE TITLE
imagenet教师模型显存不足

### ISSUE THREAD

**Issue by Takersflames** [zhengli97/PromptKD#8]
请问，在跑imagenet的教师模型的时候，batchsize设为1，16G的V100都会爆显存。但是剩下10个数据集采用batchsize=8跑教师模型都只用了大概6G左右的显存。这是为什么呢？按理来说输入图片都被resize成224×224的话，显存占用不应该会差距太大吧，而且是只有数据集不一样，CLIP模型和prompt模型方法都是一样的情况下显存占用差距有这么大。还请为我解惑，十分感谢。

**Comment by zhengli97** [comment]
因为ViT-L/14本身大，然后变成了500 class，所以吃显存。要跑起来的话需要24G 3090那种卡或者A100，推荐可以直接用已有的pretrained ViT-L/14 CLIP。PromptKD没这个显存的问题，在imagenet上bs=8情况下显存占用小于6G。

**Comment by zhengli97** [comment]
嗯嗯 不客气 有问题可以再交流 我的邮箱zhengli97@mail.nankai.edu.cn
